---
title: 'rIDIMS: An R Package for Processing Intermittent and Direct Injection Mass Spectrometry Data'
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE) 
set.seed(12345)
print_paged_df <- function(...) {
cat(rmarkdown:::print.paged_df(rmarkdown::paged_table(...,options = list(rows.print = 5))))
}

n.total.features.replicate.filter = 1
n.total.features.replicate = 10
input.replicate.filter = "TRUE"

plot.rem.feat <- "a"
plot.before.rem.feat <- "b"
input.value.replicate.filter = 99

```


```{r, results = 'asis'}
cat('\n\n## {.tabset}  \n\n')

```


```{r, results='asis'}
  #cat('## Tabs panel {.tabset}   \n')

if ( (n.total.features.replicate.filter <  n.total.features.replicate) && (input.replicate.filter == "TRUE")) {
  #cat('\n\n### Total of removed features = ', n.total.features.replicate - n.total.features.replicate.filter  ,'  \n\n') 
  cat('\n\n Procedure for removing features from replicas (specified in samples_info) that show variation greater than',(input.value.replicate.filter),'%.
The figure below illustrates the removal through the colors lightbrown (ion removal) and turquoise blue (ion permanence) ' , '\n')
  #print(plot.rem.feat)

  cat('\n')
  cat('\n\n### Dataset after procedure', '\n')
  cat('\n')
     print(plot.rem.feat)
  cat('\n')
  cat('\n\n### Dataset bb procedure', '\n')
  cat('\n')
    print(plot.before.rem.feat)
  cat('\n')
  cat( '## {-}', '\n\n')

  
  cat('fim')

}else{
  cat('\n\n### No features have been removed.  \n\n') 
}

################
################  --- end of replicate filter
################


```



